development:
  secret_mail_base: 'silvia.abreu@wolox.com'
test:
 secret_mail_base: 'silvia.abreu@wolox.com'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_mail_base: <%= ENV["SECRET_MAIL_BASE"] %>